### ISSUE TITLE
Antennae masking masks portion of head near eyespot.  (Unmasking/drawing tool?)

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#10]
We are unable to place any checkpoints closer to the eye in some of the images, where the antennae are automatically masked. 

![screen shot 2018-09-14 at 9 03 00 am](https://user-images.githubusercontent.com/43250118/45551805-fd0e1400-b7fc-11e8-81ac-dcf8b2e84e74.png)
![screen shot 2018-09-14 at 8 57 17 am](https://user-images.githubusercontent.com/43250118/45551583-63defd80-b7fc-11e8-8f8e-ea276e982d77.png)
![screen shot 2018-09-14 at 9 05 44 am](https://user-images.githubusercontent.com/43250118/45551986-74dc3e80-b7fd-11e8-93ac-661912cb1039.png)

**Comment by awedwards** [comment]
Added https://github.com/awedwards/daphnia/commit/3a123900fe5f4c3fffc205a5b5d767994f6a41b3

**Comment by rjp5nc** [comment]
Unmasking tool works as well
