### ISSUE TITLE
add 'Saving' indicator

### ISSUE THREAD

**Issue by awedwards** [awedwards/daphnia#11]
So we don't have to rely on spinning wheel to know if things are done saving or not

**Comment by awedwards** [comment]
added in https://github.com/awedwards/daphnia/commit/63b859aa60b861c866177c0cf39f3194d8d9b2e5

**Comment by rjp5nc** [comment]
After most recent update, gives this error:
![screen shot 2018-09-25 at 9 42 36 am](https://user-images.githubusercontent.com/43250118/46018375-b8f5fb80-c0a7-11e8-9162-f275c478a27c.png)

**Comment by rjp5nc** [comment]
Update: params text file does not appear to be ignored when updating.

**Comment by awedwards** [comment]
Yeah, that's annoying. I'll figure out why, but in the mean time it would definitely be worth saving a local copy of your file.

**Comment by awedwards** [comment]
Ok, I removed the params files from the repo. Shouldn't mess with your local files when you pull again in the future.
