### ISSUE TITLE
Errors when program is starting up

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#12]
We started having this issue after the update ~2 days ago. 

![screen shot 2018-09-26 at 9 53 33 am](https://user-images.githubusercontent.com/43250118/46152778-b928ff00-c23f-11e8-9599-8061de28d9ec.png)

**Comment by awedwards** [comment]
Is the params.txt file still there? Should be in the top level "daphnia" folder

**Comment by rjp5nc** [comment]
There isn't a params.txt file. The one that we have previously modified, and is currently present, is the gui_params.txt

**Comment by rjp5nc** [comment]
Working now
