### ISSUE TITLE
GUI crashes when picture isn't found, 

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#14]
It sounds like it crashed in the middle of using the program when it couldn't find the picture, and we aren't sure if it saved the previous ones. It now will not open up properly. This can probably be resolved by deleting that line, but we would like if there was a "skip" function if it didn't find the picture.

![screen shot 2018-10-15 at 1 20 49 pm](https://user-images.githubusercontent.com/43250118/46966975-2c72a380-d07d-11e8-95df-a842b5b0e825.png)

**Comment by rjp5nc** [comment]
Issue may have been due to a lack of stage micrometer picture, so we are filtering them out. Seems like another issue was compounded with this though. When starting up from a save, the program freaks out and skips through all the pictures one by one, moving through them at about one every quarter second. The only buttons that pop up are "Mark as Modified" or "Accept changes". It does appear that the images might've been saved before the issue happened, though

**Comment by awedwards** [comment]
If you clicked "Save" at any point, the data from previous images should definitely be saved.

I'd think the 'Next' button should function fine for skipping lines that don't have associated images. Or would it be best to just have the GUI automatically skip over the line (maybe printing out to the console that it skipped) and go on to the next one with an image?

**Comment by awedwards** [comment]
Regarding the "freakout", has this always happened when loading up from a previous save? Or is this a new problem?

**Comment by rjp5nc** [comment]
I think just having it erroring out isn't a good idea, since we might not have been able to actually press the save button before it errors out. If you could make it so that the next button would automatically skip images it can't find, I think that would be great. Would it be possible to also have that save to the csv file in the notes section, too? 

The "freakout" had only happened maybe twice in the past, both from loading from a save. It isn't a big issue, but it seems like this time it happened when we were in the middle of pictures, when a different error was occurring (Lack of a picture). I wasn't around when it happened, though. I don't think thats a big issue, since it usually happens after we have a save, and it isn't often.

**Comment by awedwards** [comment]
Yep, agreed. Erroring out is not ideal. I'll push an update soon!

**Comment by awedwards** [comment]
Hey just to double check, did you mean to have the path to the image be **/Users/aob-lab/Documents/Daphnia_phenotyping**, as shown in your error trace? I see it in **/mnt/spicy_4/daphnia/data**, which is why I ask.

**Comment by awedwards** [comment]
Ok! I pushed https://github.com/awedwards/daphnia/commit/6195aafca226545506d7be704119709c70f09618 to fix the issue. Let me know if it works/doesn't work!

**Comment by rjp5nc** [comment]
ok, will test it out later. Will it just print out that it was skipped, and just move to the next picture? Also, any idea on the other issue, with setting up the other computer? It seems to be almost running, except it stops at that step.

**Comment by awedwards** [comment]
It will print out what was skipped and move on to the next picture and it should also make a note in the modification_notes field that the image couldn't be found.

Re: other computer, haven't had a chance to look at the issue but I'll get back to y'all soon.
