### ISSUE TITLE
Setting up new computer

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#15]
Hi Austin,

We are setting up another computer in the office to run the program, and we are now getting this error. Any ideas? 

/Users/aob-lab/Library/Python/2.7/lib/python/site-packages/openpyxl/reader/worksheet.py:318: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
Loading 11_12_Inductions_Metadata.xlsx
Loading 12_03_Inductions_Metadata.xlsx
Loading 07_23_Inductions_Metadata.xlsx
Loading 08_13_Inductions_Metadata.xlsx
Loading 07_16_Inductions_Metadata.xlsx
Loading 06_05_Inductions_Metadata.xlsx
Loading 07_09_Inductions_Metadata.xlsx
Loading 06_18_Inductions_Metadata.xlsx
Loading 11_26_Inductions_Metadata.xlsx
Loading 12_10_Inductions_Metadata.xlsx
Loading 05_29_Inductions_Metadata.xlsx
Loading 06_12_Inductions_Metadata.xlsx
Loading 10_23_Inductions_Metadata.xlsx
Loading 07_30_Inductions_Metadata.xlsx
Loading 12_17_Inductions_Metadata.xlsx
Loading 09_18_Inductions_Metadata.xlsx
Loading 10_02_Inductions_Metadata.xlsx
Loading 10_08_Inductions_Metadata.xlsx
Loading 05_22_Inductions_Metadata.xlsx
Loading pond and season metadata

Reading in image file list
Reading in analysis file
Traceback (most recent call last):
  File "./daphnia/gui.py", line 760, in <module>
    v = Viewer(gui_params, params)
  File "./daphnia/gui.py", line 467, in __init__
    clone = utils.dfrow_to_clone(self.data, np.where(self.data.filebase == fileparts[-1])[0][0], self.params)
  File "/Users/aob-lab/Library/Python/2.7/lib/python/site-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'filebase'
biol-bergland-IM2011:daphnia aob-lab$

**Comment by awedwards** [comment]
The "DataFrame" object is basically a big table converted from the daphnia_output.txt file. If an attribute can't be found there, it might be because the daphnia_output file was loaded in incorrectly.

Could you make sure there are local copies of daphina_output and shape_output, and that the paths in gui_params properly point to these copies?

**Comment by rjp5nc** [comment]
Hmm, maybe I accidentally changes something when moving the files around. Redownloaded it again, and it worked. Thanks!
