### ISSUE TITLE
Checkpoints not connecting

### ISSUE THREAD

**Issue by awedwards** [awedwards/daphnia#2]
Oftentimes the checkpoints don't connect. Suspect it has to do with interpolation (don't even know if it does interpolation currently, might just only fill existing pixel edges)

**Comment by rjp5nc** [comment]
I believe this was due to a problem with the images, where a line had a brief gap in it, and the line refused to go over it. Hasn't been a big problem since adding the masking tool

**Comment by awedwards** [comment]
Ok, we can close it for now and revisit if it's a problem in the future.
