### ISSUE TITLE
question: mounted volume 

### ISSUE THREAD

**Issue by beckerdoerthe** [awedwards/daphnia#20]
Austin, we set-up another computer, and it seems like the mounted volumes (i.e. that /Volumes/daphnia) is always disappearing, plus I need to do the sshfs command to link it to the mnt/spicy_4 directory. I have no idea why this computer is always unmounting the drive. Do you have any ideas? If there isn't anything that comes up immediately, no worries, I can simply start each round of pictures with some more scripting lines. Just thought to briefly check in with you if there were an easy fix ;-)

**Comment by awedwards** [comment]
Not sure why that's happening. But apparently there is a 'reconnect' option for the sshfs command. You can add it right after the "-o". Maybe it will help?

i.e. sudo sshfs -o reconnect,allow_other,defer_permissions, ...

https://unix.stackexchange.com/questions/14143/what-is-a-better-way-to-deal-with-server-disconnects-of-sshfs-mounts

**Comment by beckerdoerthe** [comment]
sounds good. will try that. thanks!!
