### ISSUE TITLE
output.txt >> limit output to input set

### ISSUE THREAD

**Issue by beckerdoerthe** [awedwards/daphnia#22]
Austin, can we limit the output.txt files to just save the subset that we provide as input? I.e. each output.txt would only save modifications for those 50 pictures that we use as input?

**Comment by awedwards** [comment]
Either way, this should be working now (right now, they will save only if they have been accepted and are in the input list).

I added a parameter called 'truncate_output'. To use this feature, simply add it to your gui_params.txt file and set it to 1. Let me know if you have questions!

**Comment by beckerdoerthe** [comment]
I think, saving it when it is accepted would be good. So, just as it is now (i.e., when adding the truncate output stuff to the params txt).

**Comment by rjp5nc** [comment]
Update: It didn't actually save anything. The save file is blank, except for the column titles.

**Comment by awedwards** [comment]
Did you add a truncate_output flag to your gui_params? It won't work without it.

**Comment by rjp5nc** [comment]
Whoops, completely missed that little bit. I can test it first thing on Monday

**Comment by rjp5nc** [comment]
I added the truncate_output option, but it now gives this error when saving. It does appear to be saving and truncating the output. 

![screen shot 2018-11-06 at 8 19 13 am](https://user-images.githubusercontent.com/43250118/48088764-d226b780-e1d0-11e8-87ae-890a4383d3c5.png)
