### ISSUE TITLE
Issue from resuming from a save

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#25]
After encountering the last error (#24), I had saved and exited the program. Now, when I try to resume the session, the program will not start up, and gives this error: 

![screen shot 2018-11-08 at 12 55 19 pm](https://user-images.githubusercontent.com/43250118/48217698-12637280-e356-11e8-9d8f-b15f993d8258.png)

**Comment by awedwards** [comment]
fixed, i think!
