### ISSUE TITLE
tail_spine_length not updating.

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#26]
Changing the points for an individuals tail spine changes the values for their location, but does not update the "tail_spine_length". 

![screen shot 2018-11-19 at 8 59 49 am](https://user-images.githubusercontent.com/43250118/48711528-85cc7600-ebd9-11e8-9a8a-d3548670007e.png)

I just tested it with a few individuals, but these lengths aren't normal. I didn't have any broken tail individuals in here. 

![screen shot 2018-11-19 at 8 42 59 am](https://user-images.githubusercontent.com/43250118/48710687-279e9380-ebd7-11e8-87a6-6bc403687ef5.png)

**Comment by awedwards** [comment]
Ahh so I was calculating tail_spine_length by finding the difference between tail_tip and "tail_dorsal" (which is basically the very last point of the blue dorsal line), and the point that you can move around in the GUI is the "tail" point. Super confusing.

I'll update the code to define the tail_spine_lengrh as tail_tip to tail to make it more consistent.

**Comment by rjp5nc** [comment]
In that case, could you also make sure "tail dorsal" is also updating, too? For the one image up there, I had moved the checkpoints (Including the last one), around quite a bit to see if everything else was updating.

**Comment by awedwards** [comment]
Ok, this should work now.

For clarity:
1) tial_spine_length = euclidean distance between "tail_tip" and "tail" (previously, was tail_tip to tail_dorsal)
2) tail_dorsal should now update with the dorsal edge

Here's a diagram, just to make sure we're all on the same page.

<img width="970" alt="daphnia_diagram" src="https://user-images.githubusercontent.com/4247855/48733517-bc18ee00-ebf7-11e8-9b79-313fb7385eed.png">

**Comment by beckerdoerthe** [comment]
Great. Is 'dorsal_area' still calculated from tail_dorsal to that checkpoint near the eye? Just double checking.

**Comment by awedwards** [comment]
yes, that's right

**Comment by awedwards** [comment]
But it wasn't updating properly 😓... fixed now!
