### ISSUE TITLE
Remove automatic masking feature?

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#27]
Quite a number of images that are messed up have something wrong with the automatic masking feature. Would it be too much of an issue to test the gui without it? Even the ones that don't have much of an issue still need to be manually masked/unmasked due to it cutting off odd edges. 

![screen shot 2018-11-23 at 11 57 21 am](https://user-images.githubusercontent.com/43250118/48954428-76219a00-ef17-11e8-928d-510acdc34482.png)

**Comment by awedwards** [comment]
Sure. I will have to run the full pipeline again, but I can do that over the weekend for sure.

Just FYI in the case of the screenshot you posted, pressing "Flip" should help (this is what it looks like when the dorsal-ventral axes have been erroneously flipped).

**Comment by rjp5nc** [comment]
Actually, that one didn't need to be flipped. It does weird stuff when sections are masked like that, but sometimes we can tell based on where the line goes around the eye. It gives this error when we try to flip it. Even after unmasking it, it wouldn't let me flip it.

![screen shot 2018-11-23 at 1 05 20 pm](https://user-images.githubusercontent.com/43250118/48956347-90ac4100-ef20-11e8-8e85-f9e04ee68b1c.png)

 Moving the points slightly to the right after unmasking makes it mostly correct itself, though.

**Comment by beckerdoerthe** [comment]
Austin, do you think this update of the pipeline will affect the pictures we already ran through - i.e., their modifications? Do you think we should go ahead and check more pics or would you rather suggest to wait for the updated pipeline? Thanks!

**Comment by awedwards** [comment]
Since you're saving all of your modifications in separate files from the input file, it shouldn't affect anything you've already done. I think you can go ahead and keep fixing things.

I didn't get to run the pipeline over the weekend -- couldn't log into the workstation (sounds like there was a power outage?). I'll try to start it today, and I'll let you know when it's done!

**Comment by awedwards** [comment]
I ran the pipeline without masking. I put the analysis output files in /mnt/spicy_4/daphnia/analysis/analysis_results/*_no_masking_20181126.txt

I also had to make some changes to the gui code so remember to git pull and to point the gui_params to wherever you copy these files. Let me know if things go wrong.

**Comment by rjp5nc** [comment]
This appears to be working well now.
