### ISSUE TITLE
Last image not found = breaks gui

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#28]
If the last image in a list isn't found (Such as in block xfo), the gui crashes to a grey screen. We aren't able to save or go back. 

![screen shot 2018-11-27 at 9 26 57 am](https://user-images.githubusercontent.com/43250118/49088410-3a444880-f227-11e8-8438-032ef679aaf6.png)

**Comment by awedwards** [comment]
Weird. I'll look into it

**Comment by rjp5nc** [comment]
If possible, this one might be slightly higher priority. Its pretty rough when we reach the last picture in the block, and it completely crashes everything without warning. Even if we save ~halfway through, we lose a number of pictures

**Comment by awedwards** [comment]
I'm still trying to figure out the best way to handle this, but I pushed a quick fix. It will just clear the screen but not all of the buttons, so you'll at least be able to save.

I'll keep working on it to make the program handle this error a little more nicely.

**Comment by beckerdoerthe** [comment]
Sounds good! Thanks!

**Comment by awedwards** [comment]
OK! I pushed a more elegant fix. Let me know how it goes.

**Comment by beckerdoerthe** [comment]
Brilliant. Will check it out in the AM.

**Comment by rjp5nc** [comment]
It appears that it will not load any other images than the first one in the list. 

![screen shot 2018-11-30 at 8 21 53 am](https://user-images.githubusercontent.com/43250118/49291681-25f78a00-f479-11e8-8e13-d9ec53f3ddcf.png)

**Comment by awedwards** [comment]
Sorry about that. Fixed, hopefully.

**Comment by rjp5nc** [comment]
Awesome, both things work.
