### ISSUE TITLE
GUI has trouble with masking, then unmasking

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#34]
It looks like the update went well, and it seems to record masking fairly well. It doesn't record any unmasking that we do, though.

Is there any way to differentiate between masking and unmasking, too? I am a bit worried about pictures we need to mask/unmask several times. Maybe is there a way to set an order to the maskings/unmasking (1st masking is 1, 2nd masking is 2, unmasking is 3). That way we can tell when the final masked/unmasked image looked like?

For this picture, I masked the dorsal half of the daphnia, then unmasked the dorsal edge. It only shows the section that was masked. 

![screen shot 2018-12-18 at 9 09 48 am](https://user-images.githubusercontent.com/43250118/50159540-eb795400-02a4-11e9-883b-84100d89ab3e.png)

In this picture, I made a complex shape (a flower) to make sure it was recording it down properly. I then unmasked a section of it (the bar through the center). It recorded the shape well, but not the bar. 

![screen shot 2018-12-18 at 9 08 59 am](https://user-images.githubusercontent.com/43250118/50159523-e1efec00-02a4-11e9-9f17-9f598a228791.png)

Overlapping maskings seems to be fine, with it recording each set properly (S with a bar through it)

![screen shot 2018-12-18 at 8 59 56 am](https://user-images.githubusercontent.com/43250118/50159659-33987680-02a5-11e9-81d8-8cd84aa26671.png)

Trying to mask pictures that have already been saved gives this error:
![screen shot 2018-12-18 at 9 19 05 am](https://user-images.githubusercontent.com/43250118/50159973-13b58280-02a6-11e9-9900-56fae4a602f6.png)

**Comment by rjp5nc** [comment]
Trying to move checkpoints after saving and bringing up pictures again breaks the image and gives this error, too:

![screen shot 2018-12-18 at 2 55 09 pm](https://user-images.githubusercontent.com/43250118/50179475-1e3b4080-02d5-11e9-8340-a94ecce2f7fd.png)

**Comment by awedwards** [comment]
Unmasking works now. I added a column in the output file, 'm' or 'u', that tells whether or not the region is a mask or unmask. The regions are saved in the order they are performed by the user.

As for the saving stuff, that will take a while to implement. I think a work around would be to save to a new region masking output file if you load up a set you're halfway through. If that doesn't work, let me know.

**Comment by rjp5nc** [comment]
It seems to be something in daphnia output causing the error. Changing the masking output file doesn't fix it. If I change the daphnia output file, and leave everything else (Metadata, shape output, and masking output) the same, it works again.

**Comment by awedwards** [comment]
Weird. Ok, I'll dig in a little deeper.

**Comment by rjp5nc** [comment]
It seems to happen when checkpoints are moved and saved, or when an area is masked/unmasked. Not doing anything to the picture can allow you to save and come back to it, and still move things around. Just moving a checkpoint (without masking/unmasking), or just masking/unmasking also crashes the image. Moving checkpoints give the 2nd error I posted, while masking/unmasking gives the first one. If you just move a checkpoint, or just mask an area, it can give both errors depending on what you do.
