### ISSUE TITLE
Resetting image still saves previous maskings/unmaskings.

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#35]
It looks like if you mask an area, then the image needs to be reset, previous maskings/unmaskings are still uploaded to the masked_image_output when you save the final version. Do you think there is anywhere else in the other outputs that may be similar to this, where resetting doesn't fully reset the image?

![screen shot 2018-12-27 at 12 09 58 pm](https://user-images.githubusercontent.com/43250118/50488434-87573e00-09d0-11e9-8e5b-3a7fe0179da5.png)

**Comment by rjp5nc** [comment]
Masked areas are also still saved in the file even if the image isn't marked as "Accept changes", too.

**Comment by awedwards** [comment]
Sure, I'll look into these. This should be the only thing that 'reset' is missing, but I'll double check to make sure.

**Comment by awedwards** [comment]
Fixed

**Comment by rjp5nc** [comment]
Its still saving the masked areas even when "Accept changes" isn't being pressed (i.e., if you work on several images and press accept changes on each one, then move to the next image and mask an area, and then press save without pressing accept changes on that image, it still saves the masked area for that image anyways, without saving it in any of the other output files. This is a bit of a problem as the program is unintentionally saving stuff it shouldn't.) 

Resetting does work now.

**Comment by awedwards** [comment]
Oops, forgot to add an "if accepted" line in the saving part of the code. It should work now.

**Comment by rjp5nc** [comment]
This has been fixed
