### ISSUE TITLE
Changing blur resets image masking, but still saves previous maskings

### ISSUE THREAD

**Issue by rjp5nc** [awedwards/daphnia#38]
When a picture is masked, then the blur is changed, the masking goes away on the image (sort of like it is being reset). The maskings that no longer show up nor influence the checkpoints are still saved in the masked_regions_output file. I'm not sure if this influences the traceback errors Dörthe was getting, but it still is an issue with the blur.

**Comment by awedwards** [comment]
fixed, good catch
