### ISSUE TITLE
Want to keep track of modifications separate from 'Accept Changes'

### ISSUE THREAD

**Issue by awedwards** [awedwards/daphnia#4]
DB: can we add a 'save original’ as a 3rd option in addition to ‘accept change’ and ‘save’ in order to differentiate between pics that were changed and those that were not (based on the ‘modified’ column); this is in addition to the previously discussed ‘flag’ button that will exclude any pics that we consider not worth modifying

**Comment by awedwards** [comment]
added d3e4c0030b3963deff251281a88a2acb16b31b40

**Comment by rjp5nc** [comment]
Did we still want that "Flag" button for images that are irredeemable? "Save as Modified" works. Does the save as modified save the image similar to "accept changes"?

**Comment by awedwards** [comment]
Hmm, forgot about that. Maybe we can just include something in notes field, then you can filter out by notes? What do you think @beckerdoerthe?

**Comment by beckerdoerthe** [comment]
Actually, given that all the other issues seem to have been resolved, I feel like there are so few images that might not be redeemable... So, yes, we can simply put a specific note in the text box and filter afterwards for those - if we were to have another look at them or such.
