### ISSUE TITLE
Analysis file mismatch

### ISSUE THREAD

**Issue by awedwards** [awedwards/daphnia#6]
DB: in the output file, there are a few columns that turned up anew and/or their input changed (e.g., from numbers to TRUE vector etc); could you have a look at these columns:

 tail tip / tail base / anterior_mask_endpoints / deyecenter_pedestal_max / dorsal residual / automated_PF  (Robert will include this file in his email).

**Comment by awedwards** [comment]
seems like this is only happening for Male images, so probably an issue with parsing

**Comment by awedwards** [comment]
should be fixed, going to run full analysis tonight to check

https://github.com/awedwards/daphnia/commit/cd2b1ac4db8cea61733dcd52f7b978ab32bcacf5

**Comment by awedwards** [comment]
OK, think this should do it. I checked the columns you listed specifically, and they looked good.

https://github.com/awedwards/daphnia/commit/53fe261fda22decac34be904edd965f47ef72e50

**Comment by rjp5nc** [comment]
Columns are now in the correct alignment
