### ISSUE TITLE
Skip_accepted not working properly

### ISSUE THREAD

**Issue by awedwards** [awedwards/daphnia#7]
Accepted images aren't being purged from the clone_list properly. The 'accepted' state and changes seem to be working, but they still show up in the GUI.

**Comment by awedwards** [comment]
Think this has to do with the input file loading step, which also affects #1

**Comment by rjp5nc** [comment]
#1 now works, but the images still aren't being saved/skipped.

**Comment by rjp5nc** [comment]
Appears to be working now.

**Comment by rjp5nc** [comment]
Appears to be working fine for multiple times in a row
